In [1]:
import pandas as pd

data = {
    "Product": [
        "Laptop",
        "Phone",
        "Tablet",
        "Monitor",
        "Keyboard"
    ],
    "Sales": [
        1200,
        900,
        None,
        300,
        150
    ],
    "Region": [
        "North",
        "South",
        "North",
        "West",
        "East"
    ]
}

df = pd.DataFrame(data)

df

    Product   Sales Region
0    Laptop  1200.0  North
1     Phone   900.0  South
2    Tablet     NaN  North
3   Monitor   300.0   West
4  Keyboard   150.0   East

In [7]:
df.info()
df.describe()

df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Product  5 non-null      str
 1   Sales    4 non-null      float64
 2   Region   5 non-null      str
dtypes: float64(1), str(2)
memory usage: 252.0 bytes

Product    0
Sales      1
Region     0
dtype: int64

In [9]:
df['Sales'] = df["Sales"].fillna(df['Sales'].median())

In [16]:
df['Sales']
print(df)

    Product   Sales Region
0    Laptop  1200.0  North
1     Phone   900.0  South
2    Tablet   600.0  North
3   Monitor   300.0   West
4  Keyboard   150.0   East

In [13]:
df.loc[1,"Sales"]
df.iloc[0,2]

'North'

In [20]:
df.loc[df["Sales"].idxmax()]

Product    Laptop
Sales      1200.0
Region      North
Name: 0, dtype: object

In [22]:
df.groupby("Region")["Product"].sum()

Region
East         Keyboard
North    LaptopTablet
South           Phone
West          Monitor
Name: Product, dtype: str

In [23]:
df

    Product   Sales Region
0    Laptop  1200.0  North
1     Phone   900.0  South
2    Tablet   600.0  North
3   Monitor   300.0   West
4  Keyboard   150.0   East

In [25]:
df.groupby('Product')["Sales"].sum().sort_values(ascending=False)

Product
Laptop      1200.0
Phone        900.0
Tablet       600.0
Monitor      300.0
Keyboard     150.0
Name: Sales, dtype: float64

In [34]:
df = {"customerID":['C1','C2','C3',],
                  "purchase":[100,200,500]}

df1 = pd.DataFrame(df)

In [35]:
df1

  customerID  purchase
0         C1       100
1         C2       200
2         C3       500

In [37]:
df1.groupby('purchase')['customerID']
df1

  customerID  purchase
0         C1       100
1         C2       200
2         C3       500

In [38]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns